version: "3.7"
services:
  mysql:
    image: mysql:latest
    container_name: docker-mysql
    environment:
      MYSQL_DATABASE: pruebas
      MYSQL_USER: casita
      MYSQL_PASSWORD: casita
      MYSQL_ROOT_PASSWORD: casita
    volumes:
      - persistencia:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    command: --default-authentication-plugin=mysql_native_password

  app:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql

    
  #web:
  #  build:
  #    context: .
  #  container_name: docker-php
  #  ports:
  #    - "80:80"
  #  volumes:
  #    - ./www:/var/www/html
  #  links:
  #    - mysql

volumes:
  persistencia: